name: Unit tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Unit Test
        run: ./gradlew test
      - name: Unit tests results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit test reports
          path: kotlin-data-wedge-lib/build/test-results/*/*.xml
          reporter: java-junit
          fail-on-error: true