name: Upload release github

on:
  push:
    tags:
      - release.**

jobs:
  upload:
    environment: build
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_AUTH_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
      - name: Upload
        run: ./gradlew publish
